import { AntdRegistry } from "@ant-design/nextjs-registry";
import type { Metadata } from "next";
import "@/globals.css";
import { inter } from "@/ui/fonts";

import TopNav from "@/ui/navigation/TopNav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialised mx-auto`}>
        <AntdRegistry>
          <TopNav />
          <main>{children}</main>
        </AntdRegistry>
      </body>
    </html>
  );
}
